print("*"*50)
print("这是一个私人定制的名片程序")
company=input("请输入你的公司：")
name=input("请输入你姓名：")
position=input("请输入你的职位：")
phone=input("请输入你的电话号码：")
e_mail=input("请输入你的电子邮箱地址：")
print("*"*50)
print("公司名称 ： %s " % (company))
print()
print("姓名(职位) ：  %s( %s ) " % (name,position))
print()
print("电话：%s " % (phone))
print("*" * 50)
